### ISSUE TITLE
[Feature Request] Is it possible to add custom styles to the Library and Store views?

### ISSUE THREAD

**Issue by mikeloeven** [ungstein/OG-Steam#1]
Unsure of the limitations of the skinning system but is there any way to modify the library and store views to match the skin color scheme?

**Comment by ungstein** [comment]
Try <a href="https://github.com/ungstein/OG-Steam-Library">OG-Steam-Library<a> theme for use with <a href="https://github.com/PhantomGamers/SteamFriendsPatcher">SteamFriendsPatcher<a>. Note that this will only modify the Library. As far as I know, the Store page cannot be modified, as it is hosted externally.
