### ISSUE TITLE
Steam Overlay notification box

### ISSUE THREAD

**Issue by leonill007** [ungstein/OG-Steam#11]
The Steam Overlay notification box looks a bit different i guess (found screenshot of the old one?).
![82117](https://user-images.githubusercontent.com/64586733/134787216-9c7f2e39-3ac8-42f8-9f66-084cc160bafe.png)
.
![82117](https://user-images.githubusercontent.com/64586733/134787221-fdbd1c42-f2e2-4c8d-9c92-c8d02d1c7039.jpg)
.

**Comment by ungstein** [comment]
Thanks for providing this. I never found a screenshot of the old notification box.

**Comment by ungstein** [comment]
I made it look similar, but using the colour scheme of OG-Steam

![NotificationBox](https://i.imgur.com/r2UBqif.png)

I'll push it with the next update.
