### ISSUE TITLE
WineTahomaBit font not working

### ISSUE THREAD

**Issue by justintrotta** [ungstein/OG-Steam#12]
[https://i.ibb.co/RHp8h12/g5tfr4de3swa.png](url)

Not sure what happened. Font seemed to default to Tahoma on first launch despite the font not even being installed, after 
trying to install and launch with the new font nothing worked. The font doesn't appear in the Win10 font list but is in the list of fonts from control panel. Should I blame Microsoft?

**Comment by ungstein** [comment]
I'm gonna blame M$ for the font not appearing in the Win10 font list. Have you disabled DirectWrite through Settings/Interface?

**Comment by justintrotta** [comment]
Oh wow I'm so sorry I'm actually illiterate and incapable of reading clear instructions. Disabling directwrite fixed it! Thanks haha. Awesome work here, seriously nostalgic. Much appreciation!

**Comment by ungstein** [comment]
Glad you were able to fix it. Thanks, I hope I can bring that nostalgia to as many people as possible :)
