### ISSUE TITLE
In-game Overlay - friends overview is scrollable

### ISSUE THREAD

**Issue by LoVega1337** [ungstein/OG-Steam#14]
If you open the overlay in a game, the overview of the friends tab shows the 4 highlighted friends in a scrollable list, instead of a 2x2 grid.

How it is: 
![image](https://user-images.githubusercontent.com/47011400/142731787-fbfbcf52-ddab-488b-a8a1-e3072879cab5.png)

How it should be:
![image](https://user-images.githubusercontent.com/47011400/142731838-6f189449-fdb9-4137-8b5f-7234d7d66f46.png)

**Comment by ungstein** [comment]
Thanks for letting me know; I'll try to work out what is causing this.

**Comment by ungstein** [comment]
Turns out it was the "ScrollBar.Wide" value in steam.styles, line 343. Who would've guessed? I've pushed this update and it will be included in the next release.
