### ISSUE TITLE
Steam window icon appears in Music Player Volume slider

### ISSUE THREAD

**Issue by Mystyle-48** [ungstein/OG-Steam#17]
When using the volume slider in the Music Player, the Steam window icon appears to the left inside the box.

![MusicPlayer](https://user-images.githubusercontent.com/89315313/144667220-7f0b17ef-c38f-4d5f-b15f-b21fbdfc15ae.png)

**Comment by ungstein** [comment]
Interesting. Which OS are you running?

**Comment by Mystyle-48** [comment]
Windows 11 Home

**Comment by ungstein** [comment]
I just checked this on my machine and it is happening here, too. It looks like the volume slider is rendered in its own frame, which means it uses the frame icon. The music player was added well after the original green Steam skin was replaced, so it makes sense that it doesn't play nice with the old frame style. Unfortunately, it looks like I can't fix this.
