### ISSUE TITLE
UI has no back, forward, or reload buttons on webpages

### ISSUE THREAD

**Issue by POWERUPT** [ungstein/OG-Steam#2]
I noticed after installing the skin that it doesn't have any of the webpage controls when on a webpage, like the Steam Store or Workshop. I was using the July 20th version of the Steam stable branch, but updating to the July 30th beta did nothing. Included is a picture of the interface. 
![image](https://user-images.githubusercontent.com/36461106/127753981-60da436a-f0f5-4c66-9637-22ae924accb5.png)

**Comment by ungstein** [comment]
The nav buttons can be enabled by going to Settings > Interface and checking "Display web address bars when available".

**Comment by POWERUPT** [comment]
Alright, thank you.
