### ISSUE TITLE
Any chance for the ice blue or sand color schemes?

### ISSUE THREAD

**Issue by mz1193** [ungstein/OG-Steam#20]
Love this project, but those two variants are the ones I miss the most. It'd be neat to see them again.

**Comment by ungstein** [comment]
This is definitely something I have thought about, however there are still a few things I would like to finish on OG-Steam-Library before I add colour schemes. I have the old steamscheme.res files, which I have attached. These contain all the RGB colours for both skins. Just a matter of working out which ones go where.
[steamscheme_ice.res.txt](https://github.com/ungstein/OG-Steam/files/8390911/steamscheme_ice.res.txt)
[steamscheme_sand.res.txt](https://github.com/ungstein/OG-Steam/files/8390913/steamscheme_sand.res.txt)

**Comment by mz1193** [comment]
That's awesome news! I'm glad that's on the potential roadmap.
