### ISSUE TITLE
Middle of any screen is regular blue

### ISSUE THREAD

**Issue by BJET67** [ungstein/OG-Steam#21]
![image](https://user-images.githubusercontent.com/96207671/162672639-c791b3fc-b40f-458c-b00c-36ea3022c278.png)
![image](https://user-images.githubusercontent.com/96207671/162672659-01c55cb5-8cf0-4900-afab-4ab8897a7f1b.png)

Not sure if I did something wrong or if this is normal

**Comment by BJET67** [comment]
![image](https://user-images.githubusercontent.com/96207671/162675810-2cf43465-9f57-4dc4-8687-10f3197ae48b.png)

**Comment by gydroponch** [comment]
You can use this to apply the skin to your library! https://github.com/ungstein/OG-Steam-Library 
Other things are not meant to be changed as far as i know
