### ISSUE TITLE
missing text

### ISSUE THREAD

**Issue by jamariusquandledangle** [ungstein/OG-Steam#22]
![Capture](https://user-images.githubusercontent.com/103762268/163586670-3dd93bd6-67f3-45b9-9fb8-49c3a12b16d6.PNG)

**Comment by AgitationSkeleton** [comment]
Seconding this issue

**Comment by googleooer** [comment]
Disable "Scale text and icons to match monitor settings" and "Enable DirectWrite for improved font smoothing and kerning"

**Comment by Xenthio** [comment]
this is only an issue if you use the bit tahoma font, please disable the direct write
