### ISSUE TITLE
"Maximize Window" button missing

### ISSUE THREAD

**Issue by LoVega1337** [ungstein/OG-Steam#23]
"Maximize Window" button disappeared after recent Steam Beta update.
Looks like this now: ![image](https://user-images.githubusercontent.com/47011400/165507187-3d502a78-67ef-4225-9777-c2906abd702f.png)

**Comment by Fancy2209** [comment]
fixed yesterday by this commit: https://github.com/ungstein/OG-Steam/commit/61328dc281c192e1107e9463a8d0f3656543e224
redownload the theme

**Comment by LoVega1337** [comment]
Cheers, it's there again after removing that one line.
