### ISSUE TITLE
Missing Elements

### ISSUE THREAD

**Issue by Peltin** [ungstein/OG-Steam#24]
Some elements of the Storage Manager, Library, and Downloads menus are not present.

Running latest Beta branch of Steam as of May 13, 2022.

![broken_storagemanager](https://user-images.githubusercontent.com/104665660/168268662-1114dcb5-b3ad-4a77-bb5a-fa9e6e9ae326.png)
![broken_library](https://user-images.githubusercontent.com/104665660/168268700-29c7ab79-810e-4c97-a33b-e776d4924c5c.jpg)
![broken_downloads](https://user-images.githubusercontent.com/104665660/168269136-60cb12bd-9434-4f6d-8f49-da24d4a17e6f.png)

**Comment by Peltin** [comment]
Well, I took it upon myself to delete everything and restart from scratch. This time however I made sure 7.css was selected in SteamFriendsPatcher, ran Force Check, and everything is flawless now.

**Comment by ungstein** [comment]
Awesome, glad to hear :+1:
