### ISSUE TITLE
Top bar vanishes when viewing anything but the Library

### ISSUE THREAD

**Issue by Velken** [ungstein/OG-Steam#31]
Screenshots: https://imgur.com/a/GwxoSdP

**Comment by LoVega1337** [comment]
Yup, wanted to make an issue about this too.
This only happens on the current Beta build so I was hesitant to open an Issue since this could be fixed by Valve by the next Beta build. Or this is an intentional change and the Skins needs to adapt.

**Comment by EricTheCarrot** [comment]
The same is happening to me so I guess I have to use another skin or go back to default until this one gets fixed. :(

**Comment by Velken** [comment]
opting OUT of steam beta fixed it. no issues with SFP either

**Comment by EricTheCarrot** [comment]
> opting OUT of steam beta fixed it. no issues with SFP either

Ight I'll try that and see if the same happens to me, love this skin so i really hope this works cuz i want to keep it as my main skin.

**Comment by LoVega1337** [comment]
If you haven't noticed, there is a new version out that fixes this issue. Works like a charm for me.

**Comment by ungstein** [comment]
This has been fixed in v1.0.13. Beta users should update.
