### ISSUE TITLE
Library screen is not affected by the theme

### ISSUE THREAD

**Issue by shodanwashere** [ungstein/OG-Steam#32]
![imagem](https://user-images.githubusercontent.com/74769749/213761824-bac6c9ec-309e-4209-8930-eba063d71a0a.png)

This issue is not isolated only to the library screen. It also affects the friends list:
![imagem](https://user-images.githubusercontent.com/74769749/213761951-dddf0c32-d200-4305-8e63-b4d1bcc477af.png)

and the Download Management screen:
![imagem](https://user-images.githubusercontent.com/74769749/213762268-38c50641-c148-4f21-adee-874f092cde5d.png)

**Comment by Serif-7** [comment]
See #34 there are instructions for fixing this there.

**Comment by Kobi-Blade** [comment]
There is no theme for friends list, as for library do what **Serif** suggested.
