### ISSUE TITLE
Good news, works on Linux. Bad news, library view doesn't change.

### ISSUE THREAD

**Issue by Serif-7** [ungstein/OG-Steam#34]
![image](https://user-images.githubusercontent.com/29221564/215287704-a15b9bee-cac9-45e5-888b-7ea42b28c43f.png)

As you can see, the library view stays the same. This is fine because I can just switch to small mode, but it's annoying. I don't know if you even care to support Linux, so if you don't feel like fixing it, that's fine, but I thought I would let you know.

**Comment by Tracenji** [comment]
the library worked the last time i tried on linux
did you install [OG-Steam-Library](https://github.com/ungstein/OG-Steam-Library) using [SFP](https://github.com/PhantomGamers/SFP)?

**Comment by ungstein** [comment]
There is a Linux version of SFP that will allow you to use OG-Steam-Library.

**Comment by Serif-7** [comment]
Installing with @Tracenji instructions worked, thanks!
