### ISSUE TITLE
Steam's navigation bar visible in Library section only

### ISSUE THREAD

**Issue by tendan** [ungstein/OG-Steam#35]
Yesterday I noticed something strange about navigation bar behaviour. That one with "Store", "Library", "Community" and "<your profile name". It was visible when you were in the "Library" section only. 

Steam app restarts haven't fixed it.

Here are some screenshots visualizing the problem:
![Library](https://i.imgur.com/rLCAuxK.png)
![Store](https://i.imgur.com/Cwr1BWA.png)
![Community](https://i.imgur.com/G6UnjAA.png)
![Your profile](https://i.imgur.com/KicOxyK.png)

And here are some parameters of hardware and software that occurs on:
Steam version: 1675222618
Compilation date: Jan 31 2023
Steam language: Polish
Processor: AMD Ryzen 7 6800HS
Graphics card: Integrated AMD Radeon + NVIDIA RTX 30 Series
Operating system: Windows 11 22H2

I'll be glad for any feedback!

**Comment by JumpySWE** [comment]
Updating to the latest version 1.0.13 solved it for me.
