### ISSUE TITLE
This skin doesn't show up in interface settings when choosing it

### ISSUE THREAD

**Issue by biegbrather** [ungstein/OG-Steam#4]

**Comment by FridgeRacer** [comment]
Did you make sure to put the folder "OG-Steam" in "..\Steam\skins\"?
The downloaded zip has a folder called "OG-Steam-(version number)", you need to open that and extract the "OG-Steam" folder within that one.

I also had no "skins" folder in my Steam install directory, so you might need to make it.

![NotRocketScience](https://user-images.githubusercontent.com/40672277/120074862-1e8fb680-c09f-11eb-92fa-5b766e1c12e4.gif)

**Comment by ungstein** [comment]
Sorry for the delay; FridgeRacer is right. If the extracted folder "OG-Steam" is inside Steam\skins, it should be detected by Steam. Thank you for helping, FridgeRacer.
