### ISSUE TITLE
The library tab is not the same scheme

### ISSUE THREAD

**Issue by schrundeng** [ungstein/OG-Steam#5]
The library tab is not the same scheme

![Screenshot 2021-08-21 080008](https://user-images.githubusercontent.com/88808132/130305640-1958d696-e024-4f4e-801c-e5056cdaf096.png)

**Comment by ungstein** [comment]
Have you installed <a href=https://github.com/ungstein/OG-Steam-Library>this?</a>

**Comment by schrundeng** [comment]
the link didn't work

**Comment by ungstein** [comment]
Sorry, link edited.

**Comment by schrundeng** [comment]
Thanks
