### ISSUE TITLE
use bitmap tahoma font

### ISSUE THREAD

**Issue by Xenthio** [ungstein/OG-Steam#6]
i whipped this up for ya
[TahomaBit.zip](https://github.com/ungstein/OG-Steam/files/7095258/TahomaBit.zip)

**Comment by Xenthio** [comment]
looks like this 
![image](https://user-images.githubusercontent.com/28588188/131764657-fa14e00a-5a3f-4059-ae51-a5f52e72904d.png)

**Comment by Xenthio** [comment]
and this 
![image](https://user-images.githubusercontent.com/28588188/131765365-547dbc54-5ea4-44f8-bf25-2a6beb5bf3bf.png)

**Comment by Xenthio** [comment]
and this 
![image](https://user-images.githubusercontent.com/28588188/131765391-1ac36857-1832-4119-b010-f6ec223b0da0.png)

**Comment by ungstein** [comment]
This looks awesome! I installed the font and set basefont to "TahomaBit" in steam.styles, but now there is no text. How did you get this to work?

**Comment by Xenthio** [comment]
![image](https://user-images.githubusercontent.com/28588188/131925142-13376fa7-a907-48fc-920f-b662e389b8bf.png)
turn this off

**Comment by Xenthio** [comment]
did it work?

**Comment by ungstein** [comment]
It did, thanks. This completes the OG experience.

**Comment by Xenthio** [comment]
hooray!

**Comment by Xenthio** [comment]
will this be merged into the main theme? steam falls back to regular tahoma if the font isn't found so it should be alright if the user doesn't want to install it or forgets to

**Comment by ungstein** [comment]
I'd love to include it, but I'm just not sure about the copyright on the font. If it is an open licence, I am happy to add it as an optional font.

**Comment by Xenthio** [comment]
hmm, I can base it off of wine tahoma which is free and open source

**Comment by ungstein** [comment]
If you could, that would be awesome :+1:

**Comment by Xenthio** [comment]
wine tahoma doesnt seem to translate into a bitmap correctly and its pre baked bitmaps dont have the correct sizes that steam wants, so it looks a bit funny 
![image](https://user-images.githubusercontent.com/28588188/134268481-131563ff-841a-4e6e-bae9-5df0ede14827.png)
i'll continue trying tho

**Comment by Xenthio** [comment]
AH! ok finished! it DID have the sizes but steam didn't want to use them for some stupid reason.
![image](https://user-images.githubusercontent.com/28588188/134268935-5bed87ab-1845-44dc-9fab-c7f8495ce16e.png)

one thing about the wine tahoma is the J looks alittle funky but it's still good enough to read
![image](https://user-images.githubusercontent.com/28588188/134268947-5cd0b809-27df-4f89-b6d0-0fab4cf3a781.png)

**Comment by Xenthio** [comment]
[WineTahomaBit.zip](https://github.com/ungstein/OG-Steam/files/7207117/WineTahomaBit.zip)
oh yeah forgot to upload, heres the new wine based font (.FON) + source for editing (.SDF)

**Comment by Xenthio** [comment]
oops, i just noticed i used an old version of wines tahoma font, i'll quickly rebase my edits on the latest version

**Comment by Xenthio** [comment]
[WineTahomaBit.zip](https://github.com/ungstein/OG-Steam/files/7207148/WineTahomaBit.zip)
OK, Final version, this one still has the janky J but it's yet again still alright. 
these fonts are now based off of WINE's git://source.winehq.org/git/wine/fonts/tahoma.sfd (Mirror: https://github.com/wine-mirror/wine/blob/master/fonts/tahoma.sfd)

**Comment by Xenthio** [comment]
wine wiki (https://wiki.winehq.org/Create_Fonts) states it's license is GNU Lesser General Public License 2.1

**Comment by ungstein** [comment]
Sweet. I'll put a link to the font in README.md (crediting you and the original author) and I'll add it to the next release. Thank you for your contribution.

**Comment by Xenthio** [comment]
no problem!

**Comment by iprotecc** [comment]
> Final version, this one still has the janky J but it's yet again still alright. these fonts are now based off of WINE's git://source.winehq.org/git/wine/fonts/tahoma.sfd (Mirror: https://github.com/wine-mirror/wine/blob/master/fonts/tahoma.sfd)

Is the original not include Cyrillic, or did you not whipped it? All Cyrillic characters are invisible when using WineTahomaBit.

**Comment by SeiferLeonheart** [comment]
> ![image](https://user-images.githubusercontent.com/28588188/131925142-13376fa7-a907-48fc-920f-b662e389b8bf.png) turn this off

Request to include this in install instructions. Had the issue immediately after installing, had to search for the solution.
