### ISSUE TITLE
Unused files?

### ISSUE THREAD

**Issue by isopropyl-alco** [ungstein/OG-Steam#8]
While looking through the skins files I noticed some audio files for the friends list such as the old message sound, call sounds and friend online sounds. These don't appear to actually play, was this intentional or do these features not work? As well as these audio files I also noticed there is a special system tray icon for Windows but this doesn't appear either, these things would look and sound really cool and I would like to see them functioning in the future.

**Comment by ungstein** [comment]
I pulled a bunch of files including the ones you mentioned from very old versions of Steam. Before Friends/Chat went web-based, the audio files would be used by Steam as part of the skin. They no longer work, but I included them in case someone was able to integrate them into the new Friends/Chat. As for the tray icons, I don't think there's a way to include them without editing steam.exe, which I'm sure would cause nothing but problems. None of these files are larger than 100 KB, so I consider their disk usage to be negligible.
