### ISSUE TITLE
Friends notifications

### ISSUE THREAD

**Issue by isopropyl-alco** [ungstein/OG-Steam#9]
Notifications for friends coming online do not appear, only chat notifications appear. I am not entirely sure about this but it may also be the same for Steam group announcements. 

Also will we see a custom skin for the friends list in the future?

**Comment by ungstein** [comment]
I'm not sure why certain notifications wouldn't appear, afaik they all use the same style. I'll do some testing and see if I can replicate the problem.

**Comment by ungstein** [comment]
As for Friends/Chat, it is something a few people have asked for, but right now I can't justify the time it would take, as I don't use it. If anyone wants to have a crack, they can refer to the colour scheme and style in OG-Steam-Library, it should make the job easier.

**Comment by isopropyl-alco** [comment]
I can confirm now that It's the skin that isn't working properly, when the standard Steam skin is being used I see the onscreen notification for a friend going online and upon switching to OG-Steam it does not appear.

**Comment by ungstein** [comment]
Interesting. I'll see if I can isolate the friend notification in stock steam.

**Comment by ungstein** [comment]
Okay I've fixed the friend notification bug. It was caused by the skin not containing the file "friends\FriendOnlineNotification.res". I think the group announcements bug was similarly caused by the absence of "friends\ClanEventNotification.res" I will add these files to the next release.
